workflows:
  android-build:
    name: Android Build
    instance_type: linux_x2 # Use a Linux machine to avoid iOS errors

    scripts:
      - name: Create native folders
        script: flutter create .

      - name: Install dependencies
        script: flutter pub get

      - name: Run code generator
        script: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build the APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
