workflows:
  android-build-dopamind:
    name: Dopamind Android Build
    instance_type: linux_x2 # Use a Linux machine to avoid iOS errors

    scripts:
      - name: Create native folders
        script: | 
          set -e
          flutter create .

      - name: Install dependencies
        script: |
          set -e
          flutter pub get

      - name: Run code generator
        script: |
          set -e 
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build the APK
        script: |
          set -e
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
