name: dopamind
description: An AI-powered anti-distraction and focus mastery app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  stacked: ^3.4.0
  stacked_services: ^1.1.0
  stacked_hooks: ^0.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  cupertino_icons: ^1.0.2
  glassmorphism: ^3.0.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  logger: ^2.0.2+1
  provider: ^6.1.1
  audioplayers: ^5.2.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  stacked_generator: ^1.3.3
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
